import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0e0e0e",
        surface: "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131313",
        "surface-container": "#191a1a",
        "surface-container-high": "#1f2020",
        "surface-container-highest": "#252626",
        "surface-variant": "#252626",
        "on-surface": "#e7e5e4",
        "on-surface-variant": "#acabaa",
        "on-background": "#e7e5e4",
        primary: "#c6c6c6",
        "primary-dim": "#b8b9b9",
        "primary-container": "#454747",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#d4d4d4",
        "on-primary": "#3f4041",
        "on-primary-container": "#d0d0d0",
        secondary: "#9f9d9d",
        "secondary-dim": "#9f9d9d",
        "secondary-container": "#3c3b3b",
        "on-secondary": "#202020",
        "on-secondary-container": "#c1bfbe",
        tertiary: "#f8f9ff",
        "tertiary-dim": "#dce3ee",
        "tertiary-container": "#e5ebf7",
        "tertiary-fixed": "#eaf1fd",
        "tertiary-fixed-dim": "#dce3ee",
        "on-tertiary": "#596069",
        "on-tertiary-container": "#505761",
        "on-tertiary-fixed": "#424952",
        "on-tertiary-fixed-variant": "#5e656f",
        outline: "#767575",
        "outline-variant": "#484848",
        "inverse-surface": "#fcf9f8",
        "inverse-on-surface": "#565555",
        "inverse-primary": "#5e5f5f",
        "surface-tint": "#c6c6c6",
        error: "#ee7d77",
        "error-dim": "#bb5551",
        "error-container": "#7f2927",
        "on-error": "#490106",
        "on-error-container": "#ff9993",
      },
      fontFamily: {
        headline: ["var(--font-lexend)", "sans-serif"],
        body: ["var(--font-lexend)", "sans-serif"],
        label: ["var(--font-lexend)", "sans-serif"],
        lexend: ["var(--font-lexend)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
